### PR TITLE
feat: move away from nocrypto

### PR DESCRIPTION
**Pull request by leostera**
See #562.

### CODE REVIEW

**Comment by joseferben** [comment]
lgtm, thanks for the pr!

**Review by joseferben — APPROVED** [review]

**Comment by joseferben** [comment]
`[exception] The default generator is not yet initialized.` has the api changed for initialization?

**Comment by leostera** [comment]
Yup, my bad! I'll amend this.

**Comment by leostera** [comment]
@joseferben hi! 👋🏼 Just pushed the last fix. Managed to get all the tests passing locally too :)

**Comment by joseferben** [comment]
looks good, thank you @leostera

**Pull request merged**
