### PR TITLE
Implement file log reporter and log sources as well

### PR DESCRIPTION
**Pull request by jerben**
Make sure that the file log reporter is not using ANSI colors since
those add unnecessary noise. The CLI logger should use colored output.

### CODE REVIEW

**Review by aronerben — APPROVED** [review]

**Comment by aronerben** [comment]
Fix CI

**Comment by jerben** [comment]
> Fix CI

Done

**Comment by aronerben** [comment]
> > Fix CI
> 
> Done

I messed up the tests

**Comment by jerben** [comment]
Yeah looks like something went wrong with root path detection extraction

**Pull request merged**
